version: '3.0'

services:
  laravel:
    build:
      context: ../instalando-frameworks-em-containers/php
      dockerfile: Dockerfile
    image: caioqueiroz/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    image: caioqueiroz/nginx:prod
    build:
      context: ../ngnix-como-proxy-reverso
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - laranet
networks:
  laranet:
    driver: "bridge"