version: '3.0'

services:
  laravel:
    image: caioqueiroz/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    image: caioqueiroz/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
       - "8080:80"
networks:
  laranet:
    driver: bridge

